first commit
entertainment-veks/jv-create-annotation pull request #1
Opened 2021-01-07 12:44 UTC by entertainment-veks

2021-01-07 17:19 UTC, Ketch92 requested changes

2021-01-07 17:19 UTC, Ketch92 commented on src/main/java/core/basesyntax/model/Bet.java
> +    int value;
the task requires to add another model (User as an example) and Dao implementation for it.

2021-01-08 11:36 UTC, dmytro-hryhoruk requested changes

2021-01-08 11:36 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +    BoxDao boxDao = new BoxDaoImpl();
You should have two models and two dao classes for each of them at the result

2021-01-08 11:36 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +    BoxDao boxDao = new BoxDaoImpl();
access modifiers

2021-01-08 11:36 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            boxDao.add(box);
let's add only if dao not null and use method getAll() to print all values

2021-01-08 11:36 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/model/Box.java
> +    int weight;
access modifiers

2021-01-08 18:18 UTC, dmytro-hryhoruk requested changes

2021-01-08 18:18 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            System.out.println("Which object do you want to add?");
would be good to print all options for user

2021-01-08 18:18 UTC, dmytro-hryhoruk approved these changes
done for approve

2021-01-11 10:36 UTC, merged